appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: RfoQ+ShbYI0xw9RCNL9FvlciruFAGuebKAY3ZSR87LKhWai92CSe8rJZRrtRDisjmXMEpITIKiVeb9XAhvFZ40oNwEDyQwLCzssjH2cS+a4SJoZeFViT8yLCJOpH9mJ7jMLr6lgYFdvZV9LCESlFu/7LwLfB6oQz+XdhBjTr40ZfZjxAG5wpCOQosw9ST6kPvfSGkM0GG/EwdZOCn8fWCc5omTCXEQQGccYZnWJ+z1pidxvUSRBt8/edqMMJ7eCYEX0WJpBIEKLCNZHlSP2XjcAlaML4rL5/0up42PkKOp+Pi/14BnxnNCiYZbpknoZnV/obeXKtXS+NPEkw+dGaRCKKI+islJ1RLHRR5Z8ufXUBOVTx8JVbI5BTWnJ8z3s3gd0X5x9+LEmKkgoYzucAqbQAdeNhkzNU6xr2DPdG1utikwPl9ohP3ERALlDfZKDw5LRKHKpdVIUPG6wY3FW6VD9sLUJlE+4iu2GApK5JyxL2Xm7PDfuGRaFAbKVTgv+Cl9m/xsPyH0ENDldV5h7lQc2e2173yuaIji9X3guFhp8/VfQc9LaRIEZlsc0QbZVysWrpSwA6ZN9aJnAlzZH6cW83+ZXqMxQPazWZPCWQgyo/eIbQ8rrySSTR/2YY/Rc5fhKipMJ4PvpPEUN05kgwjCOhRg+BXusWXSLjvPfup4U=}
conda_forge_output_validation: true
